### ISSUE TITLE
Standard API messages endpoint returns nothing, rendering get_messages useless

### ISSUE THREAD

**Issue by ErikBoesen** [ErikBoesen/schoolopy#15]

**Comment by KTibow** [comment]
I'm also getting this issue in courses.

**Comment by ErikBoesen** [comment]
@AndrewLester Could you add an error for both those endpoints if nothing is returned?

**Comment by AndrewLester** [comment]
I can. I'm not exactly sure why this happens with courses but I noticed it too. `sections` worked better for me though. Also I believe messages *should* work, so I'll try to see what's up with it.

**Comment by KTibow** [comment]
> sections worked better for me though. 

I still get an error with `get_sections()`:
![image](https://user-images.githubusercontent.com/10727862/107595434-6ca0ad00-6bc9-11eb-970c-82ce7161b20e.png)

**Comment by ErikBoesen** [comment]
@AndrewLester You may want to consider categorically refactoring the way we do these `get` operations, so they don't fully crash if there's nothing returned.

**Comment by AndrewLester** [comment]
Hi, after testing a couple of endpoints with the latest version of schoolopy from the source code, it appears that there were multiple issues at play here. For one, @KTibow you are right that the standard messages endpoint does not exist. So, in #32, I made sure that one can only access the messages from a specific message folder (which is valid). Secondly, I think the reason `get_courses` and `get_sections` were failing in that way is because you may not have access to them. For example, with the newest version of the code that throws HTTPErrors for unauthorized endpoints, I got 403 forbidden responses, which I assume is on Schoology's end.
