### ISSUE TITLE
Twice of everything

### ISSUE THREAD

**Issue by justanothernoob4648** [ErikBoesen/schoolopy#17]
with open('example_config.yml', 'r') as f:
    cfg = yaml.load(f, Loader=yaml.FullLoader)

sc = schoolopy.Schoology(schoolopy.Auth(cfg['key'], cfg['secret']))
#sc.limit = 1000000  # Only retrieve 10 objects max
print(sc.get_events(section_id=XXXXXXXXXXX))

When I print it, I get 2 of everything.
[Event({'id': XXXXXXX, 'title': '', 'description': '', 'start': '2020-09-03 23:59:00', 'has_end': 0, 'end': '', 'all_day': 0, 
'editable': 0, 'rsvp': 0, 'comments_enabled': 0, 'type': 'grade_column', 'realm': 'section', 'section_id': , 'links': {'self': 'https://api.schoology.com/v1/sections/'}})]
[Event({'id': , ', 'description': '', 'start': '2020-09-03 23:59:00', 'has_end': 0, 'end': '', 'all_day': 0, 
'editable': 0, 'rsvp': 0, 'comments_enabled': 0, 'type': 'grade_column', 'realm': 'section', 'section_id': XXXXXXXXXXX, 'links': {'self': 'https://api.schoology.com/v1/sections/'}})]

like that

**Comment by justanothernoob4648** [comment]
Also, how can you access for instance, the title? It returns a list 
[Event({'id': , ', 'description': '', 'start': '2020-09-03 23:59:00', 'has_end': 0, 'end': '', 'all_day': 0,
'editable': 0, 'rsvp': 0, 'comments_enabled': 0, 'type': 'grade_column', 'realm': 'section', 'section_id': XXXXXXXXXXX, 'links': {'self': 'https://api.schoology.com/v1/sections/'}})]
with Event(Dictionary), how would you access the dictionary part?

**Comment by justanothernoob4648** [comment]
Again, (sorry for so many questions), when I do 
sc = schoolopy.Schoology(schoolopy.Auth('XXXXXXXXXX', 'XXXXXXXXXX'))
print(sc.get_courses)
I get<bound method Schoology.get_courses of <schoolopy.main.Schoology object at 0x05F50898>>
How do you decode it? I have seen this before when requesting for urls using urllib, but you could just decode that and read it, how do you do that with this?

**Comment by ErikBoesen** [comment]
For your double-printing issue, I'm not sure what would be going on, as that behavior does not happen for me when I run your code. It is possible you have some sort of client-side issue with your editor or shell.

The dictionary is mostly there so you can easily read the properties, however, you access the properties with dot notation as shown in the example scripts. So in this case, the title of the event, assuming `event` is an event object like the one you listed, would be `event.title`. If you wish to access the raw data dictionary, you can do that like so: `event.json()['title']`.

You don't need to "decode" anything—your issue in that code snippet is that you're printing the method itself, not the result of the method. `sc.get_courses()`—note the parentheses—would give you the course data. `sc.get_courses` is the literal method `get_courses`, which is why it prints it out like it does.

**Comment by ErikBoesen** [comment]
Update: I forgot you can also access properties of the dictionary directly, without needing to call `.json()`. So, `event['title']`, `event.title`, and `event.json()['title']` are all the same thing in effect.

**Comment by justanothernoob4648** [comment]
Thanks!
