### ISSUE TITLE
How to handle schoology authorization in a mobile app

### ISSUE THREAD

**Issue by jwizenfeld04** [ErikBoesen/schoolopy#36]
In the three legged authorization example there is a line input("Press enter when ready..."). From my understanding this line is meant to stall the program until the user clicks the authorize button on schoology's end so the code won't throw an error when the line auth.authorize() executes. I am creating an app that will authorize users with schoology but this method of stalling with input() won't work in an app setting because the user isn't accessing a terminal. Is there another way to stall the program until the user authorizes with schoology so the code won't throw an error automatically or is there another way to go about this problem. Thanks in advance!

**Comment by AndrewLester** [comment]
Yes, you're correct in that the `input` call is just to give the user time to authorize the request tokens through the Schoology website. The three-legged example itself does get the job done in terms of demonstrating three-legged authentication, but it may not be the best example of a real world implementation of three-legged OAuth. I say this because it involves shipping the service's `CONSUMER_KEY` and `CONSUMER_SECRET` to the client, which are values you don't want anyone to have access to. Unfortunately, I think this is an inevitable flaw in OAuth 1.0 since it was designed for use on websites.

Ideally, you'll have a web server that can act as a proxy for any Schoology API requests, meaning it will do all Schoology authentication and data fetching. Your app can then make requests to this web server to get any data it needs from custom endpoints. This does mean a lot of work, and it also means you'll have to implement another form of authentication logic between your own webserver and the app.

That said, if you wish to provide a "wait" in a mobile app for testing or because you trust who's using it, I would recommend opening a WebView/browser with the authorization URL and leaving a button of some sort visible on your app for the user to click when they return from authorization. Once they click the button, you'll know if they clicked "Authorize" vs "Cancel" on the Schoology authorization page if your request to retrieve access tokens goes through or not.

**Comment by jwizenfeld04** [comment]
I am currently building the mobile app using django rest framework and react native so I'm assuming that should solve the problem with the Consumer Key and Secret as django would serve as the web server proxy with custom endpoints. Thanks again.
