### ISSUE TITLE
Redirect Callback URL Doesn't work

### ISSUE THREAD

**Issue by nicholasxwang** [ErikBoesen/schoolopy#47]
The redirect callback doesn't work. Additionally, this happens:
<img width="596" alt="Screen Shot 2022-06-04 at 8 04 14 PM" src="https://user-images.githubusercontent.com/80929436/172033189-3c9e1ad9-ea0d-40ad-9081-b062c90d9ede.png">
Also, the authorization randomly fails. Is there an easy way to authorize with the api without random failures?

**Comment by ErikBoesen** [comment]
Could you provide errors clarifying what you mean by 1) "doesn't work" and 2) "randomly fails"? It's hard to debug with broad descriptions like that.

**Comment by nicholasxwang** [comment]
It doesn't redirect to the callback.

**Comment by jwizenfeld04** [comment]
Not sure if I'm having the exact same issue, but it seems that since Powerschool bought Schoology they finally changed the URLs and the authentication flow no longer works. Anytime I try to go to www.schoology.com it redirects me to a sub-category on the Powerschool website. Subsequently, the authentication URL no longer works as it redirects to Powerschool and says that the URL was not found (404 error).

**Comment by jwizenfeld04** [comment]
Also, I'm using the latest version of schoolopy from PyPI (0.2.2) but the Github repo says (0.2.3) so also if you can upload that as the newest version so I can install it with pip. Thank you.

**Comment by nicholasxwang** [comment]
They fixed the issue. The Oauth works for me, just the Schoology home page is weird.

**Comment by ErikBoesen** [comment]
Sounds good!
